return {
	bot_api_key = 'readapikey',
	admin = readowner,
	log_chat = -122946087,
	channel = '@readchannel',
	lang = 'languages.lua',
	plugins = {
		'onmessage.lua',
		'sera.lua',
		'all.lua',
		'mod.lua',
		'banhammer.lua',
		'users.lua',
		'help.lua',
    		'error.lua',
		'rules.lua',
		'settings.lua',
		'about.lua',
		'flag.lua',
		'service.lua',
		'links.lua',
		'warn.lua',
		'extra.lua',
		'setlang.lua',
		'floodmanager.lua',
		'mediasettings.lua',
		'admin.lua',
		'caracola.lua',
		'say.lua',
		'comprimirlink.lua',
		'sendfiles.lua',
		'killer.lua',
		'beta.lua',
		'saludador.lua',
		'italic.lua',
		'contact.lua',
	--	'spam.lua',
		'kickme.lua',
	},
	available_languages = {
		'es'
	},
	chat_data = {
		'mod',
		'owner',
		'settings',
		'about',
		'rules',
		'flood',
		'extra',
		'reportblocked',
		'media',
		'banned',
		'welcome'
	},
}
